name: End-to-end tests
on: [push]
defaults:
  run:
    working-directory: web
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: npm install & test
      #   working-directory: ./web
      #   run: |
      #     npm install
      #     npm run dev
      #     npm run test

      - name: Install Dependencies
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: web
          browser: chrome
          headless: true
          start: npm run dev
          wait-on: http://localhost:8000
