name: Integration tests
on: [push]
defaults:
  run:
    working-directory: web
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          env: true
          working-directory: web
          browser: chrome
          headless: true
          start: yarn dev
          wait-on: http://localhost:3000
        env:
          CYPRESS_UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
          CYPRESS_SANITY_USE_CDN: ${{ secrets.SANITY_USE_CDN }}
          CYPRESS_SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
          CYPRESS_SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
          CYPRESS_SANITY_API_VERSION: ${{ secrets.SANITY_API_VERSION }}
          CYPRESS_SANITY_PREVIEW_SECRET: ${{ secrets.SANITY_PREVIEW_SECRET }}
          CYPRESS_SANITY_API_TOKEN: ${{ secrets.SANITY_API_TOKEN }}
